'use client'
import { useState } from 'react'

type Campaign = {
 title:string; hook:string; devotional:string; tiktokScript:string; onScreenText:string[]; caption:string; hashtags:string[]; cta:string; visualConcept:string; imagePrompts:string[]
 bible:{primaryScripture:string; supportingScriptures:string[]; context:string; keyTruth:string; cautions:string[]}
 quality:{scriptureAccurate:boolean; biblicalConsistency:boolean; gospelCentered:boolean; audienceFit:boolean; retentionReady:boolean; notes:string[]; status:'PASS'|'REVISE'}
 status:string; growthStrategy?:GrowthStrategy|null; experiments?:any[]
}
type ImageResult={prompt:string;image:string}
type GrowthStrategy={summary:string;winningTopics:string[];winningHooks:string[];winningFormats:string[];experiments:string[];nextTopics:string[];guardrails:string[]}

const defaults={topic:'Trusting God when you cannot see the way forward',audience:'Christian youth and young adults',goal:'Encourage people to trust God, strengthen their faith, and keep following Jesus when life feels uncertain.',tone:'Bold, hopeful, warm, Jesus-centered',channels:['TikTok','Instagram Reels','YouTube Shorts']}

export default function Home(){
 const [form,setForm]=useState(defaults);const [campaign,setCampaign]=useState<Campaign|null>(null);const [images,setImages]=useState<ImageResult[]>([]);const [loading,setLoading]=useState(false);const [imageLoading,setImageLoading]=useState(false);const [error,setError]=useState('')
 const update=(k:keyof typeof form,v:any)=>setForm(f=>({...f,[k]:v}))
 async function generate(){setLoading(true);setError('');setCampaign(null);setImages([]);try{const r=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Generation failed');setCampaign(d.campaign)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function makeImages(){if(!campaign)return;setImageLoading(true);setError('');try{const r=await fetch('/api/image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompts:campaign.imagePrompts,concept:campaign.visualConcept})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Image generation failed');setImages(d.images)}catch(e:any){setError(e.message)}finally{setImageLoading(false)}}
 return <main><header className="topbar"><div className="brand"><span className="mark">✝</span><div><strong>Christian Content AI Studio</strong><small>One message • many platforms • Jesus-centered</small></div></div><div className="pill">OpenAI Responses API</div></header>
 <section className="hero"><div><div className="eyebrow">ONE MILLION SOULS • ONE MISSION</div><h1>Turn a <em>faith idea</em> into content that points people to Jesus.</h1><p>Research Scripture, build a devotional, run biblical and platform quality gates, then prepare the post for the One Million Souls autopilot.</p></div></section>
 <section className="workspace"><aside className="panel form"><div className="panelhead"><div><span className="step">01</span><h2>Message brief</h2></div><span className="muted">Required inputs</span></div>
 <label>Topic / idea<textarea value={form.topic} onChange={e=>update('topic',e.target.value)}/></label><label>Target audience<textarea value={form.audience} onChange={e=>update('audience',e.target.value)}/></label><label>Goal<textarea value={form.goal} onChange={e=>update('goal',e.target.value)}/></label><label>Tone<input value={form.tone} onChange={e=>update('tone',e.target.value)}/></label><label>Channels<input value={form.channels.join(', ')} onChange={e=>update('channels',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></label>
 <button className="primary" onClick={generate} disabled={loading}>{loading?<><span className="spinner"/>Building ministry content…</>:<>Create TikTok devotional <span>→</span></>}</button></aside>
 <section className="panel output"><div className="panelhead"><div><span className="step">02</span><h2>Content studio</h2></div>{campaign&&<span className={campaign.quality.status==='PASS'?'status':'status warn'}>{campaign.quality.status==='PASS'?'Quality passed':'Needs revision'}</span>}</div>
 {!campaign&&!loading&&!error&&<div className="empty"><div className="emptyicon">✝</div><h3>Your message will appear here</h3><p>Enter a topic and create a Scripture-grounded content package for the One Million Souls daily publishing engine.</p></div>}
 {loading&&<div className="loading"><div className="skeleton wide"/><div className="skeleton"/><div className="skeleton"/><div className="skeleton small"/></div>}
 {error&&<div className="error"><strong>Something went wrong.</strong><p>{error}</p><button onClick={generate}>Try again</button></div>}
 {campaign&&<div className="results"><article className="concept"><span className="label">TITLE</span><h3>{campaign.title}</h3><p><strong>Hook:</strong> {campaign.hook}</p><p>{campaign.devotional}</p></article>
 <div className="grid2"><article><span className="label">BIBLE FOUNDATION</span><div className="copy"><span>01</span><div><h4>{campaign.bible.primaryScripture}</h4><p>{campaign.bible.context}</p></div></div><div className="copy"><span>TRUTH</span><div><p>{campaign.bible.keyTruth}</p></div></div><div className="copy"><span>SUPPORT</span><div><p>{campaign.bible.supportingScriptures.join(' • ')}</p></div></div></article>
 <article><span className="label">QUALITY CHECK</span><ul className="checklist">{[['Scripture accurate',campaign.quality.scriptureAccurate],['Biblically consistent',campaign.quality.biblicalConsistency],['Gospel centered',campaign.quality.gospelCentered],['Audience fit',campaign.quality.audienceFit],['Retention ready',campaign.quality.retentionReady]].map(([x,v],i)=><li key={i}><span>{v?'✓':'!'}</span>{x}</li>)}</ul>{campaign.quality.notes.map((n,i)=><p className="note" key={i}>{n}</p>)}</article></div>
 <article className="copyBlock"><span className="label">TIKTOK SCRIPT</span><p>{campaign.tiktokScript}</p><span className="label">ON-SCREEN TEXT</span><ol>{campaign.onScreenText.map((x,i)=><li key={i}>{x}</li>)}</ol><span className="label">CAPTION</span><p>{campaign.caption}</p><p className="hashtags">{campaign.hashtags.join(' ')}</p><span className="label">CTA</span><p>{campaign.cta}</p></article>
 <article className="visual"><div><span className="label">VISUAL DIRECTION</span><h3>{campaign.visualConcept}</h3><p>Generate three 9:16 visual directions. You approve everything before publishing.</p></div><button className="secondary" onClick={makeImages} disabled={imageLoading}>{imageLoading?<><span className="spinner dark"/>Generating…</>:<>Generate images →</>}</button>{campaign.imagePrompts.map((p,i)=><div className="prompt" key={i}><span>Prompt {i+1}</span>{p}</div>)}{images.length>0&&<div className="imagegrid">{images.map((im,i)=><figure key={i}><img src={`data:image/png;base64,${im.image}`} alt={im.prompt}/><figcaption>{im.prompt}</figcaption></figure>)}</div>}</article>
 <div className="approval"><strong>🟢 AUTOPILOT + LEARNING</strong><span>After biblical, safety and platform checks pass, the campaign can enter the publishing queue. Performance data feeds the Growth Manager and experimentation engine.</span></div><article className="concept"><span className="label">EXPERIMENTATION ENGINE</span><h3>Test → measure → learn → repeat</h3><p>{campaign.experiments?.length ? `${campaign.experiments.length} active experiment plans are being considered for future content.` : 'The Growth Manager will create controlled hook and opening experiments as performance data accumulates.'}</p></article></div>}
 </section></section><footer><span>Browser → Next.js server → OpenAI. API key stays server-side.</span><span>Built for Jesus-centered content workflows.</span></footer></main>
}
