export const ONE_MILLION_SOULS_CAMPAIGN = {
  name: 'One Million Souls',
  mission: 'Reach people with Jesus-centered, Scripture-grounded content that encourages faith and points people to Christ.',
  mode: 'AUTOPILOT',
  publishing: {
    approvalRequired: false,
    platforms: ['TikTok', 'YouTube Shorts'],
    scheduler: 'Metricool',
    timezone: 'Africa/Johannesburg',
    chooseBestTimeFromAnalytics: true,
  },
  cadence: {
    contentRuns: 'DAILY',
    morningGeneration: true,
    targetPostsPerDay: 1,
  },
  pillars: [
    'Trust God when the way is unclear',
    'Hope when life feels difficult',
    'Prayer and dependence on God',
    'Jesus-centered encouragement',
    'Scripture explained simply',
    'Faith and obedience',
    'Testimony and transformation',
    'Gospel invitation and discipleship',
    'Short prayers people can pray today',
    'One Million Souls mission stories',
  ],
  contentFormula: [
    'STOP THE SCROLL: immediate hook',
    'CONNECT: name the real-life struggle',
    'SCRIPTURE: verified biblical foundation',
    'JESUS: center the message on Christ',
    'HOPE: give a clear, truthful takeaway',
    'ACTION: one practical faith response',
    'INVITE: encourage follow/share/comment naturally',
  ],
  qualityGates: [
    'Scripture reference and context verified',
    'No fabricated quotations or references',
    'Biblically consistent and Gospel-centered',
    'No deceptive promises or guaranteed outcomes',
    'No harmful or unsafe advice',
    'Copyright/media requirements satisfied',
    'AI-generated/altered content disclosures applied when required',
    'Platform metadata and media requirements satisfied',
  ],
  feedbackLoop: [
    'Track views and reach',
    'Track average/relative retention when available',
    'Track likes, comments, shares and follows',
    'Identify winning hooks and topics',
    'Adjust future topics, hooks and posting windows',
  ],
} as const;
